### ISSUE TITLE
Only Jan and part of Feb is making it to db-see image

### ISSUE THREAD

**Issue by glutenfreepy** [glutenfreepy/daily-stoic-api#15]
<img width="988" alt="deta-stoic-ingest-error" src="https://user-images.githubusercontent.com/27334132/129845361-80134184-1f90-4e72-a06f-e9413d23a168.png">

**Comment by glutenfreepy** [comment]
this is the script "get_json_remote.py" in the Dev branch

**Comment by bbelderbos** [comment]
`data` is a `dict` so you need to loop through it like this: `(Pdb) for k, v in data.items(): print(f"{k}\n{v}\n\b")`

**Comment by glutenfreepy** [comment]
Ahh, ok.  Thank you!  i changed that and will push changes.

**Comment by glutenfreepy** [comment]
this was due to a key in the ishan's json file that was empty "".  Issue was submitted to Ishan, and code has been modified to check for this.
